dist: bionic
env:
  global:
  - secure: 'DvgFv3NTqwnFpR4tzvvwEIc43VPyp9eDlMjtEsqUffMF9oLyRLTiUtMZEzIpGgNg4UY8cyNWv6iWHJBsmmVncow6ziDp2+cpC43zWtilZeo+ohri4ejVw16MNKaIfP2bAVU4u0QpC6xQHHDGsUyRdM6OINjQxPUqFTjjOBRggkk='
  - secure: 'PHjo7CS3U+uGxmAf9/ClQbNWUt0zfZMRuZRSwdzMc6jNy0Mp21Bl/kq/K5022yXGxaEoTF8SWzvN3pOVmUnPve71Fz85AUclzGNdLnLtOGcsE/lzXxjW+uNprLHZ9rakj9MzAlUexX6j8A5NOaxdOKOihwlNjY7xMKA5Xy+pjWA='
  - secure: 'CicwL3ulhGLS+J8yvSQt18Ta1VUOBKv9Rd60ZMzlkCoEXAoO7IvpYUwnUXE7ZurLRt1Yuif+wd3D7P4BNDFIOVw7gEYllX9S4URE+9j3I/oFze+dFpqncb15CWkCK6EIyerXs/HjZe/J1o0IwPmDTqn6KXBnP6wCNLBf4UoJBnw='
sudo: false
language: python
jobs:
  include:
  - python: '3.6'
    env: TOXENV=docs
  - python: '3.6'
    env: TOXENV=lint
  - python: '3.6'
    env: TOXENV=clean,py36,stats_xml
  - python: '3.7'
    env: TOXENV=py37
  - python: '3.8'
    env: TOXENV=py38
install:
- pip install tox
- pip install codecov
script:
- tox -v
after_success:
- codecov
after_failure:
- more .tox/log/* | cat
- more .tox/*/log/* | cat
before_deploy:
- python setup.py sdist
- python setup.py bdist_wheel
deploy:
- provider: releases
  skip_cleanup: true
  file: dist/*
  file_glob: true
  api_key:
    secure: 'AAUOGNKdh2QaTeD0BzcDcNkgA4vomSlodDxkpblXucnXkUVyQJQ8akJlGACogE6xqZ4NgLrK9cOsHO5wQyQvWKsxZSY1/c2IrKxG1Ml4X7o3kB4J/a2tERghVPQe6z/Q2rqJN6WPrWvW4k3zj7AZ8X/54H5A/u4T7scEtaIo+Cg='
  on:
    repo: autoprotocol/autoprotocol-python
    python: '3.6'
    condition: '$TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$'
- provider: pypi
  skip_cleanup: true
  username: '__token__'
  password: "$SECRET1$SECRET2$SECRET3"
  edge: true
  on:
    tags: true
    python: '3.6'
    condition: '$TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$'
